rsvp/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('rsvp.views',
    url(r'^event/(?P<slug>[A-Za-z0-9_-]+)/$', 'event_view', name='rsvp_event_view'),
    url(r'^event/(?P<slug>[A-Za-z0-9_-]+)/thanks/(?P<guest_id>\d+)/$', 'event_thanks', name='rsvp_event_thanks'),
)

rsvp/models.py
import datetime
from django.db import models
from django.db.models import permalink
from django.core.mail import send_mass_mail
from django.template import loader, Context
from django.conf import settings
from django.contrib.sites.models import Site


ATTENDING_CHOICES = (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('maybe', 'Maybe'),
    ('no_rsvp', 'Hasn\'t RSVPed yet')
)


class Event(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField()
    date_of_event = models.DateTimeField()
    verification_code = models.CharField(max_length=32, blank=True, default='', help_text='Present for future extension/guest verification.')
    email_subject = models.CharField(max_length=255, help_text='The subject line for the e-mail sent out to guests.')
    email_message = models.TextField(help_text='The body of the e-mail sent out to guests.')
    hosted_by = models.CharField(max_length=255, help_text='The name of the person/organization hosting the event.', blank=True, default='')
    street_address = models.CharField(max_length=255, help_text='The street address where the event is being held.', blank=True, default='')
    city = models.CharField(max_length=64, help_text='The city where the event is being held.', blank=True, default='')
    state = models.CharField(max_length=64, help_text='The state where the event is being held.', blank=True, default='')
    zip_code = models.CharField(max_length=10, help_text='The zip code where the event is being held.', blank=True, default='')
    telephone = models.CharField(max_length=20, blank=True, default='')
    created = models.DateTimeField(default=datetime.datetime.now)
    updated = models.DateTimeField(blank=True, null=True)
    
    def __unicode__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.updated = datetime.datetime.now()
        super(Event, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return ('rsvp_event_view', [self.slug])
    get_absolute_url = permalink(get_absolute_url)
    
    def guests_attending(self):
        return self.guests.filter(attending_status='yes')
    
    def guests_not_attending(self):
        return self.guests.filter(attending_status='no')
    
    def guests_may_attend(self):
        return self.guests.filter(attending_status='maybe')
    
    def guests_no_rsvp(self):
        return self.guests.filter(attending_status='no_rsvp')
    
    def send_guest_emails(self):
        """
        Sends an invite e-mail to all guest who have not RSVPed.
        
        Requires settings RSVP_FROM_EMAIL in your settings file. Returns a 
        count of the number of guests e-mailed.
        """
        mass_mail_data = []
        from_email = getattr(settings, 'RSVP_FROM_EMAIL', '')
        
        for guest in self.guests_no_rsvp():
            t = loader.get_template('rsvp/event_email.txt')
            c = Context({
                'event': self,
                'site': Site.objects.get_current(),
            })
            message = t.render(c)
            mass_mail_data.append([self.email_subject, message, from_email, [guest.email]])
        
        send_mass_mail(mass_mail_data, fail_silently=True)
        return self.guests_no_rsvp().count()


class Guest(models.Model):
    event = models.ForeignKey(Event, related_name='guests')
    email = models.EmailField()
    name = models.CharField(max_length=128, blank=True, default='')
    attending_status = models.CharField(max_length=32, choices=ATTENDING_CHOICES, default='no_rsvp')
    number_of_guests = models.SmallIntegerField(default=0)
    comment = models.CharField(max_length=255, blank=True, default='')
    created = models.DateTimeField(default=datetime.datetime.now)
    updated = models.DateTimeField(blank=True, null=True)
    
    def __unicode__(self):
        return u"%s - %s - %s" % (self.event.title, self.email, self.attending_status)
    
    class Meta:
        unique_together = ('event', 'email')

    def save(self, *args, **kwargs):
        self.updated = datetime.datetime.now()
        super(Guest, self).save(*args, **kwargs)

rsvp/forms.py
from django.utils.translation import ugettext as _
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from rsvp.models import ATTENDING_CHOICES, Guest


VISIBLE_ATTENDING_CHOICES = [choice for choice in ATTENDING_CHOICES if choice[0] != 'no_rsvp']


class RSVPForm(forms.Form):
    email = forms.EmailField()
    name = forms.CharField(max_length=128)
    attending = forms.ChoiceField(choices=VISIBLE_ATTENDING_CHOICES, initial='yes', widget=forms.RadioSelect)
    number_of_guests = forms.IntegerField(initial=0)
    comment = forms.CharField(max_length=255, required=False, widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        if 'guest_class' in kwargs:
            self.guest_class = kwargs['guest_class']
            del(kwargs['guest_class'])
        else:
            self.guest_class = Guest
        super(RSVPForm, self).__init__(*args, **kwargs)
    
    def clean_email(self):
        try:
            guest = self.guest_class._default_manager.get(email=self.cleaned_data['email'])
        except ObjectDoesNotExist:
            raise forms.ValidationError(_('That e-mail is not on the guest list.'), code='not_on_list')
        
        if hasattr(guest, 'attending_status') and guest.attending_status != 'no_rsvp':
            raise forms.ValidationError(_('You have already provided RSVP information.'), code='already_rsvp')
        
        return self.cleaned_data['email']
    
    def clean_number_of_guests(self):
        if self.cleaned_data['number_of_guests'] < 0:
            raise forms.ValidationError(_("The number of guests you're bringing can not be negative."), code='negative_guests')
        return self.cleaned_data['number_of_guests']
        
    def save(self):
        guest = self.guest_class._default_manager.get(email=self.cleaned_data['email'])
        
        if self.cleaned_data['name']:
            guest.name = self.cleaned_data['name']
        
        guest.attending_status = self.cleaned_data['attending']
        guest.number_of_guests = self.cleaned_data['number_of_guests']
        guest.comment = self.cleaned_data['comment']
        guest.save()
        return guest

rsvp/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.template import RequestContext
from rsvp.models import Event
from rsvp.forms import RSVPForm


def event_view(request, slug, model_class=Event, form_class=RSVPForm, template_name='rsvp/event_view.html'):
    event = get_object_or_404(model_class, slug=slug)
    
    if request.POST:
        form = form_class(request.POST)
        
        if form.is_valid():
            guest = form.save()
            return HttpResponseRedirect(reverse('rsvp_event_thanks', kwargs={'slug': slug, 'guest_id': guest.id}))
    else:
        form = form_class()
    
    return render_to_response(template_name, {
        'event': event,
        'form': form,
    }, context_instance=RequestContext(request))


def event_thanks(request, slug, guest_id, model_class=Event, template_name='rsvp/event_thanks.html'):
    event = get_object_or_404(model_class, slug=slug)
    
    try:
        guest = event.guests.get(pk=guest_id)
    except ObjectDoesNotExist:
        raise Http404
    
    return render_to_response(template_name, {
        'event': event,
        'guest': guest,
    }, context_instance=RequestContext(request))

rsvp/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    	<title>{% block title %}{% endblock %}</title>
    </head>
    
    <body>
        <div class="content">
        {% block content %}
            You probably shouldn't see this.
        {% endblock %}
        </div>
    </body>
</html>

rsvp/templates/rsvp/event_thanks.html
{% extends 'base.html' %}

{% block title %}Thanks For RSVPing To {{ event.title }}{% endblock %}

{% block content %}
    <h1>Thanks For RSVPing To {{ event.title }}</h1>
    
    <p>
        You've been placed on the 
        <a href="{% url "rsvp_event_view" event.slug %}">"{{ guest.get_attending_status_display }}" 
        list</a>.
    </p>
{% endblock %}

rsvp/templates/rsvp/event_view.html
{% extends 'base.html' %}

{% block title %}Viewing Event {{ event.title }}{% endblock %}

{% block content %}
    <h1>{{ event.title }}</h1>
    
    <p>Date: {{ event.date_of_event|date:"F j, Y @ f a" }}</p>
    
    <p>{{ event.description|linebreaksbr }}</p>
    
    <h2>Event Details</h2>
    
    {% if event.hosted_by %}
        <p>
            <strong>Hosted By:</strong>
            {{ event.hosted_by }}
        </p>
    {% endif %}
    
    {% if event.street_address %}
        <p>
            <strong>Address:</strong><br>
            {{ event.street_address }}<br>
            {{ event.city }}, {{ event.state }} {{ event.zip_code }}<br>
            {{ event.telephone }}
        </p>
    {% endif %}
    
    <h2>Will You Be Attending?</h2>
    
    <form method="post" action=".">{% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="RSVP">
                </td>
            </tr>
        </table>
    </form>
    
    <h2>Guest List</h2>
    
    {% if event.guests_attending.count %}
        <h3>Attending ({{ event.guests_attending.count }} guest{{ event.guests_attending.count|pluralize }})</h3>
    
        <ul>
            {% for guest in event.guests_attending %}
                <li>
                    {{ guest.name }}
                    {% if guest.number_of_guests %}
                        + {{ guest.number_of_guests }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    
    {% if event.guests_not_attending.count %}
        <h3>Not Attending ({{ event.guests_not_attending.count }} guest{{ event.guests_not_attending.count|pluralize }})</h3>
    
        <ul>
            {% for guest in event.guests_not_attending %}
                {% if guest.name %}
                    <li>
                        {{ guest.name }}
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    
    {% if event.guests_may_attend.count %}
        <h3>May Attend ({{ event.guests_may_attend.count }} guest{{ event.guests_may_attend.count|pluralize }})</h3>
    
        <ul>
            {% for guest in event.guests_may_attend %}
                {% if guest.name %}
                    <li>
                        {{ guest.name }}
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    
    {% if event.guests_no_rsvp.count %}
        <h3>Have Not RSVPed Yet ({{ event.guests_no_rsvp.count }} guest{{ event.guests_no_rsvp.count|pluralize }})</h3>
    
        <ul>
            {% for guest in event.guests_no_rsvp %}
                {% if guest.name %}
                    <li>
                        {{ guest.name }}
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}